---
title: "Homework 2"
author: "Uselton, Myranda"
date: "`r date()`"
output: 
  html_document:
    toc: true
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Homework 2

## Instructions 


```{r}
## load prostate data
prostate <- 
  read.table(url(
    'https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data'))

## subset to training examples
prostate_train <- subset(prostate, train==TRUE)

## plot lcavol vs lpsa
plot_psa_data <- function(dat=prostate_train) {
  plot(dat$lpsa, dat$lcavol,
       xlab="log Prostate Screening Antigen (psa)",
       ylab="log Cancer Volume (lcavol)",
       pch = 20)
}
plot_psa_data()

############################
## regular linear regression
############################

## L2 loss function
L2_loss <- function(y, yhat, ...)
  (y-yhat)^2

## fit simple linear model using numerical optimization
fit_lin <- function(y, x, loss=L2_loss, beta_init = c(-0.51, 0.75)) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*x))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}

## make predictions from linear model
predict_lin <- function(x, beta)
  beta[1] + beta[2]*x

## fit linear model
lin_beta <- fit_lin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L2_loss)

## compute predictions for a grid of inputs
x_grid <- seq(min(prostate_train$lpsa),
              max(prostate_train$lpsa),
              length.out=100)
lin_pred <- predict_lin(x=x_grid, beta=lin_beta$par)

## plot data
plot_psa_data()

## plot predictions
lines(x=x_grid, y=lin_pred, col='darkgreen', lwd=2)

## do the same thing with 'lm'
lin_fit_lm <- lm(lcavol ~ lpsa, data=prostate_train)

## make predictins using 'lm' object
lin_pred_lm <- predict(lin_fit_lm, data.frame(lpsa=x_grid))

## plot predictions from 'lm'
lines(x=x_grid, y=lin_pred_lm, col='pink', lty=2, lwd=2)


##################################
## try modifying the loss function
##################################

## custom loss function
custom_loss <- function(y, yhat)
  (y-yhat)^2 + abs(y-yhat)

## plot custom loss function
err_grd <- seq(-1,1,length.out=200)
plot(err_grd, custom_loss(err_grd,0), type='l',
     xlab='y-yhat', ylab='custom loss')

## fit linear model with custom loss
lin_beta_custom <- fit_lin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=custom_loss)

lin_pred_custom <- predict_lin(x=x_grid, beta=lin_beta_custom$par)

## plot data
plot_psa_data()

## plot predictions from L2 loss
lines(x=x_grid, y=lin_pred, col='darkgreen', lwd=2)

## plot predictions from custom loss
lines(x=x_grid, y=lin_pred_custom, col='pink', lwd=2, lty=2)


### MY CODE ###
# L1 Loss
L1_loss <- function(y,yhat, ...){
  return(abs(y-yhat))
}

# TITLTED ABSOLUTE LOSS
tilted_loss <- function(y, yhat, tau){
  ifelse(y-yhat>0, tau * (y-yhat), (tau - 1) * (y-yhat))
}

# FIT MODELS
## fit simple linear model using numerical optimization
fit_lin_tilt <- function(y, x, loss=L2_loss, beta_init = c(-0.51, 0.75), tau = 0.25) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*x, tau))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}


# PLOT L1
err_grd <- seq(-1,1,length.out=200)
plot(err_grd, L1_loss(err_grd,0), type='l',
     xlab='y-yhat', ylab='L1 loss')

# FIT DATA TO L1
lin_beta_l1 <- fit_lin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L1_loss)

lin_pred_l1 <- predict_lin(x=x_grid, beta=lin_beta_l1$par)

# FIT DATA TO TILTED WITH tau = 0.25
lin_beta_tilt_25 <- fit_lin_tilt(y = prostate_train$lcavol,
                         x = prostate_train$lpsa,
                         tau = 0.25,
                         loss = tilted_loss)
lin_pred_tilt_25 <- predict_lin(x = x_grid, beta = lin_beta_tilt_25$par)

# FIT DATA TO TILTED WITH tau = 0.75
lin_beta_tilt_75 <- fit_lin_tilt(y = prostate_train$lcavol,
                         x = prostate_train$lpsa,
                         tau = 0.75,
                         loss = tilted_loss)

lin_pred_tilt_75 <- predict_lin(x = x_grid, beta = lin_beta_tilt_75$par)

# PLOT
plot_psa_data()

lines(x = x_grid, y = lin_pred_l1, col = 'darkgreen', lwd = 2)
lines(x = x_grid, y = lin_pred_tilt_25, col = 'pink', lwd = 2)
lines(x = x_grid, y = lin_pred_tilt_75, col = 'yellow', lwd = 2)
lines(x = x_grid, y = lin_pred, col = "blue")
legend("topleft", c("L1", "L2", "Tilted, tau = 0.25", "Tilted, tau = 0.75"), lwd = c(2,2,2),col = c("darkgreen", "blue", "pink", "yellow"))

# FIT NONLINEAR MODEL

## fit simple nonlinear model using numerical optimization
fit_nonlin <- function(y, x, loss=L2_loss, beta_init = c(-1.0, 0.0, -0.3)) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*exp(-beta[3]*x)))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}

fit_nonlin_tilt <- function(y, x, loss=L2_loss, beta_init = c(-1.0, 0.0, -0.3), tau = 0.25) {
  err <- function(beta)
    mean(loss(y,  beta[1] + beta[2]*exp(-beta[3]*x), tau))
  beta <- optim(par = beta_init, fn = err)
  return(beta)
}

## make predictions from linear model
predict_nonlin <- function(x, beta)
  beta[1] + beta[2]*exp(-beta[3]*x)


# FIT DATA TO L1 - NONLINEAR
nonlin_beta_l1 <- fit_nonlin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L1_loss)

nonlin_pred_l1 <- predict_nonlin(x=x_grid, beta=nonlin_beta_l1$par)

# FIT DATA TO L2 - NONLINEAR
nonlin_beta_l2 <- fit_nonlin(y=prostate_train$lcavol,
                    x=prostate_train$lpsa,
                    loss=L2_loss)

nonlin_pred_l2 <- predict_nonlin(x=x_grid, beta=nonlin_beta_l2$par)

# FIT DATA TO TILTED WITH tau = 0.25 - NONLINEAR
nonlin_beta_tilt_25 <- fit_nonlin_tilt(y = prostate_train$lcavol,
                         x = prostate_train$lpsa,
                         tau = 0.25,
                         loss = tilted_loss)
nonlin_pred_tilt_25 <- predict_nonlin(x = x_grid, beta = nonlin_beta_tilt_25$par)

# FIT DATA TO TILTED WITH tau = 0.75 - NONLINEAR
nonlin_beta_tilt_75 <- fit_nonlin_tilt(y = prostate_train$lcavol,
                         x = prostate_train$lpsa,
                         tau = 0.75,
                         loss = tilted_loss)

nonlin_pred_tilt_75 <- predict_nonlin(x = x_grid, beta = nonlin_beta_tilt_75$par)

# PLOT - NONLINEAR
plot_psa_data()

lines(x = x_grid, y = nonlin_pred_l1, col = 'darkgreen', lwd = 2)
lines(x = x_grid, y = nonlin_pred_tilt_25, col = 'pink', lwd = 2)
lines(x = x_grid, y = nonlin_pred_tilt_75, col = 'yellow', lwd = 2)
lines(x = x_grid, y = nonlin_pred_l2, col = "blue")
legend("topleft", c("L1","L2", "Tilted, tau = 0.25", "Tilted, tau = 0.75"), lwd = c(2,2,2),col = c("darkgreen","blue", "pink", "yellow"))



```